---

- name: Assertions
  ansible.builtin.assert:
    that:
      - "pgbouncer_auth_db != 'pgbouncer'"

- name: Install
  ansible.legacy.include_tasks: install.yml
- name: Configure
  ansible.legacy.include_tasks: config.yml
- name: Start
  ansible.legacy.include_tasks: start.yml
