---

- name: Create service file
  ansible.builtin.template:
    dest: /etc/systemd/system/pgbouncer.service
    src: pgbouncer.service.j2
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart pgbouncer

- name: Start pgbouncer
  ansible.builtin.systemd_service:
    name: pgbouncer
    enabled: true
    state: started
    daemon_reload: true
